CREATE TABLE cars (
    id UUID PRIMARY KEY,
    make VARCHAR(255) NOT NULL,
    model VARCHAR(255) NOT NULL,
    year INT NOT NULL CHECK (year BETWEEN 1886 AND EXTRACT(YEAR FROM CURRENT_DATE)),
    price NUMERIC(15, 2) NOT NULL CHECK (price > 0),
    vin CHAR(17) NOT NULL UNIQUE
);
